QUIZZICAL PROJECT
haroldmud/quizzical-game pull request #1
Opened 2023-03-10 14:44 UTC by haroldmud

2023-03-14 16:29 UTC, mhenriette requested changes
the answers are predictable because they are all at the first index, try to sort them too

2023-03-14 16:29 UTC, mhenriette commented on src/App.js
> +  const [is, setIs] = useState(true)
you can try to improve state names by making them more descriptive

2023-03-14 16:29 UTC, mhenriette commented on src/App.js
> +              <li  className={`${is ? "" : "hidden"} flex h-[100vh] flex-col justify-center`}>
since you only have one alternative, you can use a logical AND operator here
```suggestion
              <li  className={`${!is  && "hidden"} flex h-[100vh] flex-col justify-center`}>
```

2023-03-14 16:29 UTC, mhenriette commented on src/operations.js
> +  const [assertOne, setAssertOne] = useState([{name: "Mudflap", isSelected: false},{name: "Ratchet", isSelected: false} ,{name: "Sideswipe", isSelected: false},{name: "Skids", isSelected: false}])
you can improve your code by making a file of data and then use it from there instead of creating  a state for each question

2023-03-14 16:29 UTC, mhenriette commented on src/operations.js
> +                  className={`${item.isSelected === true ? "bg-blue-200" : ""}  text-blues border border-blues px-2 rounded-md text-sm font-semibold `}>{item.name}</button>
you can use a logical AND operator here

2023-03-14 16:29 UTC, mhenriette commented on src/operations.js
> +            { questionOne === 0 ? <button className="text-red-500 text-2xl"><IoCloseCircle/></button> : questionOne === 1 ? <button className="text-green-500 text-2xl"><IoCheckmarkCircle/></button> :
try to format your code

2023-03-14 16:29 UTC, mhenriette commented on src/operations.js
> +                className={`${item.isSelected === true ? "bg-blue-200" : ""}  text-blues border border-blues px-2 rounded-md text-sm font-semibold `}>{item.name}</button> ) }
same here

2023-03-14 16:29 UTC, mhenriette commented on src/operations.js
> +                  className={`${item.isSelected === true ? "bg-blue-200" : ""}  text-blues border border-blues px-2 rounded-md text-sm font-semibold `}>{item.name}</button>) }
same here

2023-03-14 16:29 UTC, mhenriette commented on src/operations.js
> +                {assertThree.map((item,idx)=>
to avoid repetition, you can make a component of the question and reuse it   instead of creating and designing a container for each question

2023-03-14 16:29 UTC, mhenriette commented on src/operations.js
> +          <div><p className={`${showResult ? "" : 'hidden'} text-center font-bold text-blue-500`}>{`Your result is ${result.length} / 3`}</p></div>
same here

2023-03-14 16:29 UTC, mhenriette commented on src/operations.js
> +          <div className="mt-20 flex justify-center">{showResult ? <button onClick={()=> window.location.reload()} className="bg-blues p-4 text-white font-bold rounded-lg shadow-2xl">Next challenge</
improve by formatting your code

2023-03-30 13:24 UTC, mhenriette requested changes
Good work  @haroldmud on your great Quizzical👍🏽, you can also improve your code by implementing the changes I suggested, Thanks.

2023-03-30 13:24 UTC, mhenriette commented on src/App.js
> +      <>
you don't need the fragments here

2023-03-30 13:24 UTC, mhenriette commented on src/components/Questions.js
> +function Question({allAns,correct_ans,isShow,answer, setAnswer,setCounter}){
You can use Prettier or another code formatter to format your code.
```suggestion
function Question({allAns, correct_ans, isShow, answer, setAnswer, setCounter}){
```

2023-03-30 13:24 UTC, mhenriette commented on src/components/Questions.js
> +  console.log(answer)
you can remove this console

2023-03-30 13:24 UTC, mhenriette commented on src/components/Questions.js
> +      if(correct_ans ===value ){
```suggestion
      if(correct_ans === value ){
```

2023-03-30 13:24 UTC, mhenriette commented on src/components/operations.js
> +                <Question answer={answer} setAnswer={setAnswer} setCounter={setCounter}  isShow={check} correct_ans={item.correct_answer} allAns={[item.correct_answer, ...item.incorrect_answers]} set
you can destructure item and use its properties from there

2023-03-30 13:26 UTC, mhenriette requested changes

2023-03-30 13:26 UTC, mhenriette commented on src/components/operations.js
> +
Component file names should be in Pascal Case

2023-03-31 08:19 UTC, haroldmud commented on src/App.js
> +      <>
DONE

2023-03-31 08:20 UTC, haroldmud commented on src/components/Questions.js
> +  console.log(answer)
DONE

2023-03-31 08:22 UTC, haroldmud commented on src/components/operations.js
> +
@mhenriette  should I right "QueStion"? 👀

2023-03-31 08:22 UTC, haroldmud commented on src/components/operations.js
> +                <Question answer={answer} setAnswer={setAnswer} setCounter={setCounter}  isShow={check} correct_ans={item.correct_answer} allAns={[item.correct_answer, ...item.incorrect_answers]} set
DONE

2023-04-04 12:44 UTC, mhenriette approved these changes
Looks good

2024-01-30 07:00 UTC, merged